"""add_new_contract_fields_and_tables

Revision ID: 11b5f2bb9ca0
Revises: add_elevator_fields
Create Date: 2025-11-15 10:17:41.845800+00:00

"""
from typing import Any, cast

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '11b5f2bb9ca0'
down_revision = 'add_elevator_fields'
branch_labels = None
depends_on = None

_CURRENT_TIMESTAMP_DEFAULT: Any = cast(Any, sa.text('(CURRENT_TIMESTAMP)'))
_ZERO_TEXT_DEFAULT: Any = cast(Any, sa.text('0'))
_UNSPECIFIED_CONSTRAINT = cast(str, None)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_attachments_id'), 'contract_attachments', ['id'], unique=False)
    op.create_table('contract_elevators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('elevator_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('capacity_kg', sa.Integer(), nullable=True),
    sa.Column('capacity_persons', sa.Integer(), nullable=True),
    sa.Column('speed_mps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('num_stops', sa.Integer(), nullable=True),
    sa.Column('travel_height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('door_type', sa.String(), nullable=True),
    sa.Column('origin_country', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('emergency_system', sa.String(), nullable=True),
    sa.Column('intercom', sa.String(), nullable=True),
    sa.Column('display_screen', sa.String(), nullable=True),
    sa.Column('other_features', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('warranty_period', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_elevators_id'), 'contract_elevators', ['id'], unique=False)
    op.create_table('contract_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_payments_id'), 'contract_payments', ['id'], unique=False)
    op.drop_index('ix_file_shares_id', table_name='file_shares')
    op.drop_table('file_shares')
    op.drop_index('ix_file_versions_id', table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index('ix_file_collections_id', table_name='file_collections')
    op.drop_table('file_collections')
    op.drop_index('ix_audit_exports_id', table_name='audit_exports')
    op.drop_table('audit_exports')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_elevator_sale_pricing_id', table_name='elevator_sale_pricing')
    op.drop_table('elevator_sale_pricing')
    op.drop_index('ix_elevator_bom_id', table_name='elevator_bom')
    op.drop_table('elevator_bom')
    op.drop_index('ix_audit_summaries_id', table_name='audit_summaries')
    op.drop_table('audit_summaries')
    op.drop_index('ix_file_uploads_id', table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index('ix_file_collection_items_id', table_name='file_collection_items')
    op.drop_table('file_collection_items')
    op.drop_index('ix_file_comments_id', table_name='file_comments')
    op.drop_table('file_comments')
    op.drop_index('ix_file_download_logs_id', table_name='file_download_logs')
    op.drop_table('file_download_logs')
    op.drop_index('ix_audit_rules_id', table_name='audit_rules')
    op.drop_table('audit_rules')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_audit_anomalies_id', table_name='audit_anomalies')
    op.drop_table('audit_anomalies')
    op.alter_column('ap_invoices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ap_payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('beneficiary_distribution_decisions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('beneficiary_distribution_decisions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('beneficiary_distribution_decisions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.drop_index('ix_beneficiary_decisions_beneficiary', table_name='beneficiary_distribution_decisions')
    op.drop_index('ix_beneficiary_decisions_profit_run', table_name='beneficiary_distribution_decisions')
    op.create_index(op.f('ix_beneficiary_distribution_decisions_beneficiary_id'), 'beneficiary_distribution_decisions', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_beneficiary_distribution_decisions_id'), 'beneficiary_distribution_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiary_distribution_decisions_profit_run_id'), 'beneficiary_distribution_decisions', ['profit_run_id'], unique=False)
    op.create_unique_constraint('unique_beneficiary_decision_per_run', 'beneficiary_distribution_decisions', ['profit_run_id', 'beneficiary_id'])
    op.alter_column('company_share_beneficiaries', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('company_share_beneficiaries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('company_share_beneficiaries', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.create_index(op.f('ix_company_share_beneficiaries_id'), 'company_share_beneficiaries', ['id'], unique=False)
    op.add_column('contracts', sa.Column('seller_company_name', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('seller_address', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('seller_phone', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('seller_email', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('seller_authorized_person', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_address', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_phone', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_email', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_representative', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('project_name', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('project_location', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('building_type', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('num_floors', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('usage_type', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('warranty_period', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('seller_obligations', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_obligations', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('general_terms', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('total_amount_text', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('price_includes', sa.Text(), nullable=True))
    op.alter_column('customers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('elevator_calculation_configs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('elevators', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expense_categories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expenses', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(_UNSPECIFIED_CONSTRAINT, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'project_id')
    op.alter_column('invoice_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(_UNSPECIFIED_CONSTRAINT, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'project_id')
    op.alter_column('ownership_snapshots', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('partner_account_ledger', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('partner_account_ledger', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('partner_account_ledger', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.drop_index('idx_partner_ledger_date', table_name='partner_account_ledger')
    op.drop_index('idx_partner_ledger_partner', table_name='partner_account_ledger')
    op.create_index(op.f('ix_partner_account_ledger_id'), 'partner_account_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_partner_account_ledger_partner_id'), 'partner_account_ledger', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_account_ledger_transaction_date'), 'partner_account_ledger', ['transaction_date'], unique=False)
    op.alter_column('partner_capital_movements', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('partner_profit_payouts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('partner_profit_payouts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('partner_profit_payouts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.drop_index('idx_partner_payouts_date', table_name='partner_profit_payouts')
    op.drop_index('idx_partner_payouts_partner', table_name='partner_profit_payouts')
    op.create_index(op.f('ix_partner_profit_payouts_id'), 'partner_profit_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_partner_profit_payouts_partner_id'), 'partner_profit_payouts', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_profit_payouts_payout_date'), 'partner_profit_payouts', ['payout_date'], unique=False)
    op.alter_column('partners', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('permissions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True,
               existing_server_default=_ZERO_TEXT_DEFAULT)
    op.alter_column('products', 'stock',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True,
               existing_server_default=_ZERO_TEXT_DEFAULT)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_alerts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_configs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_distribution_lines', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_runs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_order_containers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('purchase_order_containers', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('purchase_order_containers', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.create_index(op.f('ix_purchase_order_containers_id'), 'purchase_order_containers', ['id'], unique=False)
    op.alter_column('purchase_order_installments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('purchase_order_installments', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('purchase_order_installments', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.create_index(op.f('ix_purchase_order_installments_id'), 'purchase_order_installments', ['id'], unique=False)
    op.alter_column('purchase_order_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_order_payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_orders', 'received_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sales_orders', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=False)
    op.drop_constraint(_UNSPECIFIED_CONSTRAINT, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'project_id')
    op.drop_constraint(_UNSPECIFIED_CONSTRAINT, 'service_tickets', type_='foreignkey')
    op.drop_column('service_tickets', 'project_id')
    op.alter_column('suppliers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_roles', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('suppliers', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('service_tickets', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'service_tickets', 'projects', ['project_id'], ['id'])
    op.add_column('sales_orders', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'projects', ['project_id'], ['id'])
    op.alter_column('sales_orders', 'exchange_rate',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_orders', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_orders', 'received_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('purchase_order_payments', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_order_items', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_purchase_order_installments_id'), table_name='purchase_order_installments')
    op.alter_column('purchase_order_installments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('purchase_order_installments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('purchase_order_installments', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_purchase_order_containers_id'), table_name='purchase_order_containers')
    op.alter_column('purchase_order_containers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('purchase_order_containers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('purchase_order_containers', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('profit_runs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_distribution_lines', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_configs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profit_alerts', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'stock',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=_ZERO_TEXT_DEFAULT)
    op.alter_column('products', 'cost_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=_ZERO_TEXT_DEFAULT)
    op.alter_column('permissions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('partners', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_partner_profit_payouts_payout_date'), table_name='partner_profit_payouts')
    op.drop_index(op.f('ix_partner_profit_payouts_partner_id'), table_name='partner_profit_payouts')
    op.drop_index(op.f('ix_partner_profit_payouts_id'), table_name='partner_profit_payouts')
    op.create_index('idx_partner_payouts_partner', 'partner_profit_payouts', ['partner_id'], unique=False)
    op.create_index('idx_partner_payouts_date', 'partner_profit_payouts', ['payout_date'], unique=False)
    op.alter_column('partner_profit_payouts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('partner_profit_payouts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('partner_profit_payouts', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('partner_capital_movements', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_partner_account_ledger_transaction_date'), table_name='partner_account_ledger')
    op.drop_index(op.f('ix_partner_account_ledger_partner_id'), table_name='partner_account_ledger')
    op.drop_index(op.f('ix_partner_account_ledger_id'), table_name='partner_account_ledger')
    op.create_index('idx_partner_ledger_partner', 'partner_account_ledger', ['partner_id'], unique=False)
    op.create_index('idx_partner_ledger_date', 'partner_account_ledger', ['transaction_date'], unique=False)
    op.alter_column('partner_account_ledger', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('partner_account_ledger', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('partner_account_ledger', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('ownership_snapshots', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('invoices', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'projects', ['project_id'], ['id'])
    op.alter_column('invoice_items', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('expenses', sa.Column('project_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'projects', ['project_id'], ['id'])
    op.alter_column('expenses', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expense_categories', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('elevators', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('elevator_calculation_configs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customers', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('contracts', 'price_includes')
    op.drop_column('contracts', 'total_amount_text')
    op.drop_column('contracts', 'general_terms')
    op.drop_column('contracts', 'buyer_obligations')
    op.drop_column('contracts', 'seller_obligations')
    op.drop_column('contracts', 'warranty_period')
    op.drop_column('contracts', 'usage_type')
    op.drop_column('contracts', 'num_floors')
    op.drop_column('contracts', 'building_type')
    op.drop_column('contracts', 'project_location')
    op.drop_column('contracts', 'project_name')
    op.drop_column('contracts', 'buyer_representative')
    op.drop_column('contracts', 'buyer_email')
    op.drop_column('contracts', 'buyer_phone')
    op.drop_column('contracts', 'buyer_address')
    op.drop_column('contracts', 'buyer_name')
    op.drop_column('contracts', 'seller_authorized_person')
    op.drop_column('contracts', 'seller_email')
    op.drop_column('contracts', 'seller_phone')
    op.drop_column('contracts', 'seller_address')
    op.drop_column('contracts', 'seller_company_name')
    op.drop_index(op.f('ix_company_share_beneficiaries_id'), table_name='company_share_beneficiaries')
    op.alter_column('company_share_beneficiaries', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('company_share_beneficiaries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('company_share_beneficiaries', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('unique_beneficiary_decision_per_run', 'beneficiary_distribution_decisions', type_='unique')
    op.drop_index(op.f('ix_beneficiary_distribution_decisions_profit_run_id'), table_name='beneficiary_distribution_decisions')
    op.drop_index(op.f('ix_beneficiary_distribution_decisions_id'), table_name='beneficiary_distribution_decisions')
    op.drop_index(op.f('ix_beneficiary_distribution_decisions_beneficiary_id'), table_name='beneficiary_distribution_decisions')
    op.create_index('ix_beneficiary_decisions_profit_run', 'beneficiary_distribution_decisions', ['profit_run_id'], unique=False)
    op.create_index('ix_beneficiary_decisions_beneficiary', 'beneficiary_distribution_decisions', ['beneficiary_id'], unique=False)
    op.alter_column('beneficiary_distribution_decisions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('beneficiary_distribution_decisions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=_CURRENT_TIMESTAMP_DEFAULT)
    op.alter_column('beneficiary_distribution_decisions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('ap_payments', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ap_invoices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('audit_anomalies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audit_log_id', sa.INTEGER(), nullable=True),
    sa.Column('anomaly_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), nullable=True),
    sa.Column('detected_at', sa.DATETIME(), nullable=True),
    sa.Column('detection_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('baseline_period', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('expected_value', sa.VARCHAR(length=255), nullable=True),
    sa.Column('actual_value', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deviation_percentage', sa.INTEGER(), nullable=True),
    sa.Column('context_data', sqlite.JSON(), nullable=True),
    sa.Column('related_events', sqlite.JSON(), nullable=True),
    sa.Column('is_resolved', sa.BOOLEAN(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_by', sa.INTEGER(), nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('false_positive', sa.BOOLEAN(), nullable=True),
    sa.Column('notifications_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('notification_recipients', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_anomalies_id', 'audit_anomalies', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('record_id', sa.BIGINT(), nullable=True),
    sa.Column('old_values', sa.TEXT(), nullable=True),
    sa.Column('new_values', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_table('audit_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('entity_types', sqlite.JSON(), nullable=True),
    sa.Column('actions', sqlite.JSON(), nullable=True),
    sa.Column('user_roles', sqlite.JSON(), nullable=True),
    sa.Column('conditions', sqlite.JSON(), nullable=True),
    sa.Column('audit_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('capture_old_values', sa.BOOLEAN(), nullable=True),
    sa.Column('capture_new_values', sa.BOOLEAN(), nullable=True),
    sa.Column('capture_request_data', sa.BOOLEAN(), nullable=True),
    sa.Column('capture_response_data', sa.BOOLEAN(), nullable=True),
    sa.Column('retention_period_days', sa.INTEGER(), nullable=True),
    sa.Column('compliance_tags', sqlite.JSON(), nullable=True),
    sa.Column('send_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('notification_recipients', sqlite.JSON(), nullable=True),
    sa.Column('notification_threshold', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_rules_id', 'audit_rules', ['id'], unique=False)
    op.create_table('file_download_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('download_method', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('download_size', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('is_successful', sa.BOOLEAN(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_download_logs_id', 'file_download_logs', ['id'], unique=False)
    op.create_table('file_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_text', sa.TEXT(), nullable=False),
    sa.Column('parent_comment_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['file_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_comments_id', 'file_comments', ['id'], unique=False)
    op.create_table('file_collection_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('custom_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('added_by', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['file_collections.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_collection_items_id', 'file_collection_items', ['id'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=11), nullable=True),
    sa.Column('storage_provider', sa.VARCHAR(length=12), nullable=True),
    sa.Column('s3_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('storage_bucket', sa.VARCHAR(length=100), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('thumbnail_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('upload_session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('access_permissions', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('virus_scan_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('virus_scan_result', sqlite.JSON(), nullable=True),
    sa.Column('virus_scan_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_uploads_id', 'file_uploads', ['id'], unique=False)
    op.create_table('audit_summaries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('period_start', sa.DATETIME(), nullable=False),
    sa.Column('period_end', sa.DATETIME(), nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_actions', sa.INTEGER(), nullable=True),
    sa.Column('successful_actions', sa.INTEGER(), nullable=True),
    sa.Column('failed_actions', sa.INTEGER(), nullable=True),
    sa.Column('unique_users', sa.INTEGER(), nullable=True),
    sa.Column('unique_entities', sa.INTEGER(), nullable=True),
    sa.Column('action_breakdown', sqlite.JSON(), nullable=True),
    sa.Column('entity_breakdown', sqlite.JSON(), nullable=True),
    sa.Column('user_breakdown', sqlite.JSON(), nullable=True),
    sa.Column('high_risk_actions', sa.INTEGER(), nullable=True),
    sa.Column('critical_actions', sa.INTEGER(), nullable=True),
    sa.Column('security_events', sa.INTEGER(), nullable=True),
    sa.Column('compliance_violations', sa.INTEGER(), nullable=True),
    sa.Column('financial_transactions', sa.INTEGER(), nullable=True),
    sa.Column('total_amount_affected', sqlite.JSON(), nullable=True),
    sa.Column('large_transactions', sa.INTEGER(), nullable=True),
    sa.Column('avg_response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('slowest_operations', sqlite.JSON(), nullable=True),
    sa.Column('anomalies_detected', sa.INTEGER(), nullable=True),
    sa.Column('anomaly_details', sqlite.JSON(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_summaries_id', 'audit_summaries', ['id'], unique=False)
    op.create_table('elevator_bom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('component_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('warehouse_section', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_elevator_bom_id', 'elevator_bom', ['id'], unique=False)
    op.create_table('elevator_sale_pricing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('pricing_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('height_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('section_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('rope_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('cable_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('motor_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('door_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('installation_cost', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('maintenance_cost', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('profit_percentage', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('profit_amount', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('final_price', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=_CURRENT_TIMESTAMP_DEFAULT, nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_elevator_sale_pricing_id', 'elevator_sale_pricing', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.create_table('audit_exports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('export_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('user_ids', sqlite.JSON(), nullable=True),
    sa.Column('entity_types', sqlite.JSON(), nullable=True),
    sa.Column('actions', sqlite.JSON(), nullable=True),
    sa.Column('audit_levels', sqlite.JSON(), nullable=True),
    sa.Column('categories', sqlite.JSON(), nullable=True),
    sa.Column('total_records', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('requested_by', sa.INTEGER(), nullable=True),
    sa.Column('requested_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('export_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('retention_until', sa.DATETIME(), nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), nullable=True),
    sa.Column('access_log', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_exports_id', 'audit_exports', ['id'], unique=False)
    op.create_table('file_collections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('allow_uploads', sa.BOOLEAN(), nullable=True),
    sa.Column('max_file_size', sa.INTEGER(), nullable=True),
    sa.Column('allowed_file_types', sqlite.JSON(), nullable=True),
    sa.Column('parent_collection_id', sa.INTEGER(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_collection_id'], ['file_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_collections_id', 'file_collections', ['id'], unique=False)
    op.create_table('file_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('version_comment', sa.TEXT(), nullable=True),
    sa.Column('changes_summary', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_versions_id', 'file_versions', ['id'], unique=False)
    op.create_table('file_shares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_with_user_id', sa.INTEGER(), nullable=True),
    sa.Column('shared_with_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('share_token', sa.VARCHAR(length=64), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('max_downloads', sa.INTEGER(), nullable=True),
    sa.Column('download_count', sa.INTEGER(), nullable=True),
    sa.Column('can_view', sa.BOOLEAN(), nullable=True),
    sa.Column('can_download', sa.BOOLEAN(), nullable=True),
    sa.Column('can_edit', sa.BOOLEAN(), nullable=True),
    sa.Column('requires_login', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_accessed', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_file_shares_id', 'file_shares', ['id'], unique=False)
    op.drop_index(op.f('ix_contract_payments_id'), table_name='contract_payments')
    op.drop_table('contract_payments')
    op.drop_index(op.f('ix_contract_elevators_id'), table_name='contract_elevators')
    op.drop_table('contract_elevators')
    op.drop_index(op.f('ix_contract_attachments_id'), table_name='contract_attachments')
    op.drop_table('contract_attachments')
    # ### end Alembic commands ###
