"""Add stock and cost_price columns to products

Revision ID: b1fd9007a2d5
Revises: 40911042241a
Create Date: 2025-10-01 11:39:12.595340+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fd9007a2d5'
down_revision = '40911042241a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_elevator_bom_id', table_name='elevator_bom')
    op.drop_table('elevator_bom')
    op.drop_index('ix_elevator_sale_pricing_id', table_name='elevator_sale_pricing')
    op.drop_table('elevator_sale_pricing')
    op.drop_index('ix_projects_code', table_name='projects')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_table('projects')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'project_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'project_id')
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('purchase_orders', sa.Column('received_date', sa.Date(), nullable=True))
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'project_id')
    op.drop_constraint(None, 'service_tickets', type_='foreignkey')
    op.drop_column('service_tickets', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tickets', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'service_tickets', 'projects', ['project_id'], ['id'])
    op.add_column('sales_orders', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'projects', ['project_id'], ['id'])
    op.drop_column('purchase_orders', 'received_date')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'cost_price')
    op.add_column('invoices', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'projects', ['project_id'], ['id'])
    op.add_column('expenses', sa.Column('project_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'projects', ['project_id'], ['id'])
    op.create_table('projects',
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('contract_no', sa.VARCHAR(length=100), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("status IN ('PLANNED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED')", name='check_project_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.create_index('ix_projects_code', 'projects', ['code'], unique=False)
    op.create_table('elevator_sale_pricing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('pricing_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('height_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('section_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('rope_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('cable_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('motor_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('door_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('installation_cost', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('maintenance_cost', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('profit_percentage', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('profit_amount', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('final_price', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_elevator_sale_pricing_id', 'elevator_sale_pricing', ['id'], unique=False)
    op.create_table('elevator_bom',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('component_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.Column('warehouse_section', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_elevator_bom_id', 'elevator_bom', ['id'], unique=False)
    # ### end Alembic commands ###